version: '3.8'
services:
  db:
    image: postgres:15.1
    env_file:
      - .env
    ports:
      - 5440:5432
    volumes: 
      - holaplex_hub_webhooks:/var/lib/postgresql/data

  #SVIX
  backend:
    image: svix/svix-server
    platform: linux/amd64
    environment:
      WAIT_FOR: "true"  # We want to wait for the default services
      SVIX_REDIS_DSN: "redis://redis:6379"
      # SVIX_DB_DSN: "postgresql://holaplex:holaplex@pgbouncer/svix"
      DATABASE_URL: "postgresql://holaplex:holaplex@svix-postgres:5432/svix?max_conns=500&max_idle_conns=100"
      SVIX_JWT_SECRET: ${SVIX_JWT_SECRET}
    ports:
      - "8071:8071"
    depends_on:
    - svix-postgres
    - redis
    networks:
      - svix

  svix-postgres:
    image: postgres:13.4
    ports:
      - "5232:5432"
    volumes:
      - "svix-postgres-data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: holaplex
      POSTGRES_DB: svix
      POSTGRES_PASSWORD: holaplex
    networks:
      - svix
  redis:
    image: "redis:7.0.8-alpine"
    # Enable persistence
    command: "--save 60 500 --appendonly yes --appendfsync everysec"
    volumes:
      - "svix-redis-data:/data"  
    networks:
      - svix
networks:
  svix:
volumes:
  holaplex_hub_webhooks:
    driver: local
  svix-postgres-data:
  svix-redis-data: