version: '3.8'
services:
  db:
    image: postgres:15.2
    env_file:
      - .env
    ports:
      - 5440:5432
    volumes: 
      - holaplex_hub_webhooks:/var/lib/postgresql/data

  redpanda:
    image: redpandadata/redpanda:v23.1.1
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 9644:9644
      - 29092:29092

  #SVIX
  backend:
    image: svix/svix-server
    platform: linux/amd64
    environment:
      WAIT_FOR: "true"  # We want to wait for the default services
      SVIX_REDIS_DSN: "redis://redis:6379"
      # SVIX_DB_DSN: "postgresql://holaplex:holaplex@pgbouncer/svix"
      DATABASE_URL: "postgresql://holaplex:holaplex@svix-postgres:5432/svix?max_conns=500&max_idle_conns=100"
      SVIX_JWT_SECRET: ${SVIX_JWT_SECRET}
    ports:
      - "8071:8071"
    depends_on:
    - svix-postgres
    - redis
    networks:
      - svix

  svix-postgres:
    image: postgres:15.2
    ports:
      - "5232:5432"
    volumes:
      - "svix-postgres-data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: holaplex
      POSTGRES_DB: svix
      POSTGRES_PASSWORD: holaplex
    networks:
      - svix
  redis:
    image: redis:7.0.9
    # Enable persistence
    command: "--save 60 500 --appendonly yes --appendfsync everysec"
    volumes:
      - "svix-redis-data:/data"  
    networks:
      - svix
networks:
  svix:
volumes:
  holaplex_hub_webhooks:
    driver: local
  svix-postgres-data:
  svix-redis-data: