version: '3.8'
services:
  db:
    image: postgres:15.1
    env_file:
      - .env
    ports:
      - 5440:5432
    volumes: 
      - holaplex_hub_webhooks:/var/lib/postgresql/data
volumes:
  holaplex_hub_webhooks: