//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "organization_applications")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub svix_app_id: String,
    #[sea_orm(unique)]
    pub organization_id: Uuid,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::webhooks::Entity",
        from = "Column::OrganizationId",
        to = "super::webhooks::Column::OrganizationId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Webhooks,
}

impl ActiveModelBehavior for ActiveModel {}
