//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::{
    organization_applications::Entity as OrganizationApplications, webhooks::Entity as Webhooks,
    webhook_projects::Entity as WebhookProjects,
};
